### ISSUE TITLE
[Feature request] Add TXT Record to Blink

### ISSUE THREAD

**Issue by DiscordDigital** [fedejaure/mdns-beacon#40]
## Expected Behavior
Adding an argument to pass a TXT record to the announced service

## Actual Behavior
There's no argument for that

I need to add a txt record, however that doesn't seem to be an option.
If I'm just really blind or don't know how to use it please correct me.
I looked at the help options as well.

Thank you!

Best regards
DiscordDigital

**Comment by fedejaure** [comment]
Unfortunately that feature is not implemented yet. I could try to add it in a few days.

**Comment by DiscordDigital** [comment]
That'd be cool, take your time and thank you!

**Comment by fedejaure** [comment]
This should be fixed in the last version (0.3.0).
